version: "3.3"

services:
  # Payments
  payments_db:
    image: postgres
    environment: 
      - POSTGRES_DB=payments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: -p 5433
    networks: 
      my_net:
        ipv4_address: 172.26.1.3
        
  payments_app:
    build: 
      context: .
      dockerfile: payments_app/Dockerfile
    command: bash -c "python manage.py makemigrations && 
                      python manage.py migrate && 
                      python manage.py runserver 172.26.1.1:1111"
    restart: on-failure:5
    ports:
      - "1111:1111"
    expose: 
      - "1111"
    depends_on:
      - payments_db
      - kafka
    networks: 
      my_net:
        ipv4_address: 172.26.1.1

  # Refunds
  refunds_db:
    image: postgres
    environment: 
      - POSTGRES_DB=refunds
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: -p 5434
    networks: 
      my_net:
        ipv4_address: 172.26.1.4

  refunds_app:
    build: 
      context: .
      dockerfile: refunds_app/Dockerfile
    command: bash -c "python manage.py makemigrations && 
                      python manage.py migrate && 
                      python manage.py runserver 172.26.1.2:2222"
    restart: on-failure:5
    ports:
      - "2222:2222"
    expose: 
      - "2222"
    depends_on:
      - refunds_db
      - kafka
    networks: 
      my_net:
        ipv4_address: 172.26.1.2
  
  # See:
  # https://hub.docker.com/r/bitnami/zookeeper
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: "zookeeper_container"
    networks:
      - "my_net"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # See:
  # https://hub.docker.com/r/bitnami/kafka
  kafka:
    image: bitnami/kafka:2.5.0
    container_name: "kafka_container"
    restart: on-failure:5
    networks:
      - "my_net"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

networks:
  my_net:
    ipam: 
      driver: default
      config:
        - subnet: 172.26.0.0/16
