# Generated by Django 2.2.12 on 2021-09-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbway',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='base',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'credit_card'), ('mbway', 'mbway')], max_length=50),
        ),
        migrations.AlterField(
            model_name='base',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('error', 'error'), ('settled', 'settled')], max_length=20),
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
        migrations.DeleteModel(
            name='MbWay',
        ),
    ]
