# Generated by Django 2.2.12 on 2021-09-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_creditcard_mbway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'credit_card'), ('mbway', 'mbway')], default='credit_card', max_length=50),
        ),
        migrations.AlterField(
            model_name='base',
            name='settled_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='payment_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.Base'),
        ),
        migrations.AlterField(
            model_name='mbway',
            name='payment_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.Base'),
        ),
    ]
